name: centos-64bit

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux]
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: make clean
    - name: api
      run: |
        make --directory=docs/api
	cd docs/api
        api-upload.sh
    - name: build
      run: make
    - name: debug
      run: make DEBUG=yes
    - name: shared
      run: make shared
    - name: zip
      run: |
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_centos_zip
        path: build/admb.zip
    - name: manuals
      run: PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH make --directory=docs/manuals
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: manuals_pdfs
        path: build/manuals
    - name: tests
      run: make test DEBUG=yes
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs-opt.txt
