name: windows-latest-mingw-dist

on: [push]

jobs:
  build:

    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: |
        set PATH=C:\msys64\mingw64\bin;%PATH%
        utilities\\make clean
    - name: msys64 mingw64
      run: |
        set PATH=C:\msys64\mingw64\bin;%PATH%
        utilities\\make DEBUG=yes
      shell: cmd
    - name: rtool40 mingw64
      run: |
        set PATH=C:\rtools40\mingw64\bin;%PATH%
        utilities\\make DEBUG=yes
      shell: cmd
    - name: rtool35 mingw64
      run: |
        set PATH=C:\rtools35\mingw64\bin;%PATH%
        utilities\\make DEBUG=yes
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_zip_distribution
        path: build\\admb.zip
