name: windows-latest-mingw-64bit

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: run windows-latest-debug
      run: |
        utilities\\make clean
        utilities\\make DEBUG=yes
        utilities\\make test DEBUG=yes
      shell: cmd
