name: windows-latest-debug

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd & nmake clean DEBUG=yes
    - name: build
      run: pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd & nmake DEBUG=yes
    - name: tests
      run: pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd & nmake tests DEBUG=yes
