name: windows-latest-mingw-64bit

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: run windows-latest-debug
      run: |
        set PATH=C:\msys64\mingw64\bin;%PATH%
        utilities\\make USE_MINGW_PATH=C:\\msys64\\mingw64\\bin clean
        utilities\\make USE_MINGW_PATH=C:\\msys64\\mingw64\\bin DEBUG=yes
        utilities\\make test USE_MINGW_PATH=C:\\msys64\\mingw64\\bin DEBUG=yes
      shell: cmd
